[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "B5s9QSxi3oVqux9y6cu1QbFrymN2gbJhGfdS7DzpcFfG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/shreyas0924/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
